export const meals_single = {
  "meals": [
    {
      "idMeal": "53013",
      "strMeal": "Big Mac",
      "strDrinkAlternate": null,
      "strCategory": "Beef",
      "strArea": "American",
      "strInstructions": "For the Big Mac sauce, combine all the ingredients in a bowl, season with salt and chill until ready to use.\r\n2. To make the patties, season the mince with salt and pepper and form into 4 balls using about 1/3 cup mince each. Place each onto a square of baking paper and flatten to form into four x 15cm circles. Heat oil in a large frypan over high heat. In 2 batches, cook beef patties for 1-2 minutes each side until lightly charred and cooked through. Remove from heat and keep warm. Repeat with remaining two patties.\r\n3. Carefully slice each burger bun into three acrossways, then lightly toast.\r\n4. To assemble the burgers, spread a little Big Mac sauce over the bottom base. Top with some chopped onion, shredded lettuce, slice of cheese, beef patty and some pickle slices. Top with the middle bun layer, and spread with more Big Mac sauce, onion, lettuce, pickles, beef patty and then finish with more sauce. Top with burger lid to serve.\r\n5. After waiting half an hour for your food to settle, go for a jog.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=C5J39YnnPsg",
      "strIngredient1": "Minced Beef",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Sesame Seed Burger Buns",
      "strIngredient4": "Onion",
      "strIngredient5": "Iceberg Lettuce",
      "strIngredient6": "Cheese",
      "strIngredient7": "Dill Pickles",
      "strIngredient8": "Mayonnaise",
      "strIngredient9": "White Wine Vinegar",
      "strIngredient10": "Pepper",
      "strIngredient11": "Mustard",
      "strIngredient12": "Onion Salt",
      "strIngredient13": "Garlic Powder",
      "strIngredient14": "Paprika",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "400g",
      "strMeasure2": "2 tbs",
      "strMeasure3": "2",
      "strMeasure4": "Chopped",
      "strMeasure5": "1/4 ",
      "strMeasure6": "2 sliced",
      "strMeasure7": "2 large",
      "strMeasure8": "1 cup ",
      "strMeasure9": "2 tsp",
      "strMeasure10": "Pinch",
      "strMeasure11": "2 tsp",
      "strMeasure12": "1 1/2 tsp ",
      "strMeasure13": "1 1/2 tsp ",
      "strMeasure14": "1/2 tsp",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
}

export const drinks_single = {
  "drinks": [
    {
      "idDrink": "178319",
      "strDrink": "Aquamarine",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Martini Glass",
      "strInstructions": "Shake well in a shaker with ice.\r\nStrain in a martini glass.",
      "strInstructionsES": "Agite bien en una coctelera con hielo. Cuela en una copa de Martini.",
      "strInstructionsDE": null,
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare bene in uno shaker con ghiaccio.\r\nFiltrare in una coppetta Martini.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg",
      "strIngredient1": "Hpnotiq",
      "strIngredient2": "Pineapple Juice",
      "strIngredient3": "Banana Liqueur",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 oz",
      "strMeasure2": "1 oz",
      "strMeasure3": "1 oz",
      "strMeasure4": "",
      "strMeasure5": "",
      "strMeasure6": "",
      "strMeasure7": "",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": null
    }
  ]
}
